@startuml C4_Elements

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!define C4Component

!include <C4/C4_Component>

Container_Boundary(api, "API - Laravel") {
    Component(controller, "TravelController", "Controller", "Gerencia operações de rotas e viagens")
    Component(service, "RouteService", "Service", "Lógica de negócio das rotas")
    Component(repository, "Route model", "Model", "Acesso a dados das rotas")
    Component(middleware_auth, "AuthMiddleware", "Middleware", "Serviço de autenticação")
}

Component(ex_api, "AuthUser", "Endpoint", "Verifica se o usuário também está autenticado na prefeitura")

Person(user, "Usuário", "Usuário do sistema")

Component(web_app, "Frontend", "frontend")

Rel(middleware_auth, controller, "Solicita dados")
Rel(middleware_auth, ex_api, "Autentica usuário")
Rel(controller, service, "Chama serviços de rotas")
Rel(service, repository, "Acessa o modelo de dados")
Rel(user, web_app, "Usa")
Rel(web_app, middleware_auth, "Autentica usuário")

@enduml